version: '0.11.0+{build}'
image: Visual Studio 2017
skip_branch_with_pr: true
branches:
  only:
    - master
skip_commits:
  files:
  - '**/*.md'

dotnet_csproj:
  patch: true
  file: 'src\*.props'
  version: '{version}'

build:
  verbosity: minimal
services:
  - mongodb
install:
  - choco install opencover codecov
  - ps: .\build\dotnet-install.ps1 -Version 3.0.100-preview5-011568


build_script:
  - dotnet build -c Release
  - dotnet pack --no-build -c Release /p:PackageOutputPath=..\..\.nupkgs
test_script:
  - OpenCover.Console.exe -register:user -target:"%LocalAppData%\Microsoft\dotnet\dotnet.exe" -targetargs:"test tests/MongoFramework.Tests/MongoFramework.Tests.csproj /p:DebugType=Full" -filter:"+[MongoFramework]* -[MongoFramework.Tests]*" -output:".\coverage.xml" -oldstyle
  - codecov -f coverage.xml


artifacts:
  - path: '.nupkgs\*.nupkg'

  - path: coverage.xml
    name: Coverage Report